"use client";
import Image from "next/image";
import { ChevronLeft, ChevronRight, X } from "lucide-react";
import { AnimatePresence, motion, useReducedMotion } from "motion/react";
import { useEffect, useState } from "react";
import { lookbookItems } from "@/data/lookbook";
import { bookingMessage, createWhatsAppUrl } from "@/lib/whatsapp";

export function LookbookSection() {
  const [selected, setSelected] = useState<number | null>(null); const reduceMotion = useReducedMotion();
  const close = () => setSelected(null); const previous = () => setSelected(index => index === null ? null : (index - 1 + lookbookItems.length) % lookbookItems.length); const next = () => setSelected(index => index === null ? null : (index + 1) % lookbookItems.length);
  useEffect(() => { const onKey = (event: KeyboardEvent) => { if (event.key === "Escape") setSelected(null); if (event.key === "ArrowLeft") setSelected(index => index === null ? null : (index - 1 + lookbookItems.length) % lookbookItems.length); if (event.key === "ArrowRight") setSelected(index => index === null ? null : (index + 1) % lookbookItems.length); }; window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); }, []);
  return <section id="lookbook" className="bg-ink px-5 py-24 text-porcelain sm:px-10 lg:px-16 lg:py-36"><div className="mx-auto max-w-[1400px]"><div className="flex items-end justify-between gap-6"><div><p className="eyebrow text-champagne">Straight from the Enelle chair</p><h2 className="mt-7 max-w-3xl font-display text-[clamp(3.3rem,6vw,6.4rem)] leading-[.87] tracking-[-.06em]">The <span className="italic text-champagne">proof</span> is in the finish.</h2></div><a href="https://www.instagram.com/enelle_beauty_bar/" target="_blank" rel="noreferrer" className="hidden border-b border-champagne pb-2 text-[10px] font-bold uppercase tracking-[.15em] text-champagne transition hover:text-porcelain md:block">See more on Instagram</a></div>
  <div className="mt-14 grid grid-cols-2 gap-3 md:grid-cols-3 md:gap-5">{lookbookItems.map((item, index) => <button key={item.image} onClick={() => setSelected(index)} className={`group relative overflow-hidden text-left ${index === 0 || index === 3 ? "row-span-2 aspect-[3/5]" : "aspect-[4/5]"}`}><Image src={item.image} alt={item.category} fill sizes="(max-width: 768px) 50vw, 33vw" className="object-cover transition duration-700 group-hover:scale-105" /><span className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-ink via-ink/55 to-transparent px-4 pb-4 pt-14 text-[10px] font-bold uppercase tracking-[0.15em] text-porcelain opacity-100 transition group-hover:text-champagne">{item.category}</span></button>)}</div><a href="https://www.instagram.com/enelle_beauty_bar/" target="_blank" rel="noreferrer" className="mt-8 inline-block border-b border-champagne pb-2 text-[10px] font-bold uppercase tracking-[.15em] text-champagne md:hidden">See more on Instagram</a></div>
  <AnimatePresence>{selected !== null && <motion.div role="dialog" aria-modal="true" aria-label="Lookbook image" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-50 grid place-items-center bg-charcoal/95 p-5"><button onClick={close} aria-label="Close gallery" className="absolute right-5 top-5 text-cream"><X /></button><button onClick={previous} aria-label="Previous image" className="absolute left-4 text-cream sm:left-8"><ChevronLeft /></button><div className="grid max-h-full w-full max-w-5xl gap-6 md:grid-cols-[1.4fr_0.6fr] md:items-end"><div className="relative aspect-[3/4] max-h-[75svh]"><Image src={lookbookItems[selected].image} alt={lookbookItems[selected].category} fill sizes="90vw" className="object-cover" /></div><div className="text-cream"><p className="text-xs uppercase tracking-[0.2em] text-gold">{lookbookItems[selected].category}</p><p className="mt-5 font-display text-3xl">{lookbookItems[selected].caption}</p><a href={createWhatsAppUrl(`${bookingMessage} I'm interested in this ${lookbookItems[selected].category} look.`)} target="_blank" rel="noreferrer" className="mt-8 inline-block border-b border-gold pb-2 text-xs uppercase tracking-[0.15em]">Book this look</a></div></div><button onClick={next} aria-label="Next image" className="absolute right-4 text-cream sm:right-8"><ChevronRight /></button></motion.div>}</AnimatePresence>
  </section>;
}
